# Generated by Django 4.1.7 on 2023-06-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subcribe',
            field=models.ManyToManyField(blank=True, related_name='subcripbe_by', to='videos.video'),
        ),
    ]
