# Generated by Django 4.1.7 on 2023-06-04 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='videos.video'),
            preserve_default=False,
        ),
    ]
