# Generated by Django 4.1.7 on 2023-06-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_channel_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='subcribe',
        ),
        migrations.AddField(
            model_name='channel',
            name='subcribe',
            field=models.ManyToManyField(blank=True, related_name='subcripbe_by', to='videos.channel'),
        ),
    ]
