# Generated by Django 4.1.7 on 2023-06-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_remove_video_subcribe_channel_subcribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='subcribe',
            new_name='subscribe',
        ),
    ]
