# Generated by Django 4.1.7 on 2023-06-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_rename_subcribe_channel_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
