# Generated by Django 4.1.7 on 2023-06-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_savevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savevideo',
            name='save',
        ),
    ]
