# Generated by Django 4.1.7 on 2023-06-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_remove_savevideo_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.video'),
        ),
    ]
