# Generated by Django 4.2.2 on 2023-06-06 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_remove_channel_subscribe_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='channel_videos', to='videos.channel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_videos', to='videos.video'),
        ),
    ]
