# Generated by Django 4.2.2 on 2023-06-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_video_channel_alter_channel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='channel',
            name='image',
            field=models.ImageField(default='https://th.bing.com/th/id/OIP.iSu2RcCcdm78xbxNDJMJSgHaEo?pid=ImgDet&rs=1', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='social_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
